# Generated by Django 5.0.3 on 2024-03-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='order',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publish',
        ),
        migrations.AddField(
            model_name='category',
            name='display',
            field=models.BooleanField(default=False, help_text='Display, allow to display', verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='display',
            field=models.BooleanField(default=False, help_text='Display, allow to display', verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=False, help_text='Display, allow to display', verbose_name='Display'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='store.product'),
        ),
    ]
